image: ubuntu:latest

stages:
  - setup-prerequisite
  - install
  - test

Install_Java-sdk:
  stage: setup-prerequisite
  name: java-sdk 
  script:
    - sudo apt-get update -y
    - sudo apt install default-jdk -y
    - javac --version

Install_Apache-Jmeter:
  stage: install
  name: apache-jmeter
  script:
    - wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.5.zip
    - unzip apache-jmeter-5.5.zip
    - ./apache-jmeter-5.5./bin/jmeter --version
    - ./jmeter

Run_load_performance_test:
  stage: test
  name: jmeter
  script: 
    - mkdir testresults
    - ./jmeter.sh -n -t ./testcalls.jmx -l ./testresults.csv -e -o ./testresults
